version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
