inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'lib/crowdin-api/api_resources/**/*'
