name: Test and Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.0', '3.1', '3.2', '3.3' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests and linter
        run: |
          bundle exec rubocop
          bundle exec rake

      - name: Publish code coverage report
        uses: codecov/codecov-action@v3
        if: matrix.ruby-version == '3.0'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
